@startuml
[*] --> Draft
Draft : Post creado (borrador)

Draft --> Publicado 
Publicado : Post publicado

Publicado --> Eliminado 
Eliminado : Post eliminado

Publicado --> Editado 
Editado : Post en edición
Editado --> Publicado 

@enduml