@startuml
left to right direction
actor Usuario_Registrado

rectangle "Aplicación" {
    rectangle "Post"{
        usecase "Crear post" as UC3
        usecase "Comentar post" as UC4
        usecase "Dar like a post" as UC5
        usecase "Reportar post" as UC7
}
    
}


Usuario_Registrado --> UC3
Usuario_Registrado --> UC4
Usuario_Registrado --> UC5
Usuario_Registrado --> UC7
@enduml
