@startuml
title Funciones dentro de "Comunidades"

state Comunidades {
  [*] --> Selección
  Selección --> Eliminar
  Eliminar --> Selección
  Selección --> [*]
}

Comunidades --> Publicaciones
Comunidades --> Reportes
Comunidades --> Usuarios 
Comunidades --> Aplicacion
Comunidades --> [*]
@enduml
