@startuml
title Funciones dentro de "Reportes"

state Reportes {
  [*] --> Selección
  Selección --> RevisarContenido
  RevisarContenido --> Selección
  Selección --> [*]
}

Reportes --> Publicaciones: Ver publicaciones
Reportes --> Usuarios: Ver usuarios
Reportes --> Aplicacion: Ver aplicacion
Reportes --> Comunidades: Ver comunidades
Reportes --> [*]
@enduml
