@startuml
title Funciones dentro de "Usuarios"

state Usuarios {
  [*] --> Selección
  Selección --> Suspender
  Selección --> Advertir
  Selección --> Desbloquear
  Suspender --> Selección
  Advertir --> Selección
  Desbloquear --> Selección
  Selección --> [*]
}

Usuarios --> Publicaciones: Ver publicaciones
Usuarios --> Reportes: Ver reportes
Usuarios --> Aplicacion: Ver aplicacion
Usuarios --> Comunidades: Ver comunidad
Usuarios --> [*]
@enduml
