@startuml

abstract class UsuarioInvitado {}

class UsuarioRegistrado {}

class Moderador {}

class Post {}

class Etiqueta {}

class Comunidad{}

class Filtro{}

class Comentario{}

class Like{}

Comunidad o-- UsuarioRegistrado
Comunidad o-- Post
UsuarioRegistrado <--> Post
UsuarioInvitado <|-- UsuarioRegistrado
UsuarioRegistrado <|-- Moderador
Post --o Etiqueta
Post *-- Like
Post *-- Comentario
Post ..> Filtro
Filtro .> Etiqueta


@enduml
