@startuml

abstract class UsuarioInvitado {
    +String id
    +String nombre
    +File foto
    +Date fechaEntrada
    +verPost()
    +compartirPost()
}

class UsuarioRegistrado {
    +String correoInstitucional
    +List<Post> posts
    +List<Comunidad> comunidades
    +publicarPost()
    +comentarPost()
    +LikePost()
}

class Moderador {
    +eliminarPost()
    +banearUsuario()
}

class Post {
    +String id
    +Date fechaCreacion
    +Date fechaResuelto
    +int duracion
    +String contenido
    +boolean resuelto
    +Usuario creador
    +List<Etiqueta> etiquetas
    +List<Comentarios> comentario
    +List<Likes> likes
}
class Etiqueta {
     +List<Post> posts
     +List<Comunidad> comunidades
}

class Comunidad{
    +String nombre
    +File foto
    +List<Etiqueta> etiquetasAsociadas
    +List<Usuario> miembros
    +List<Post> posts
}

class Filtro{
    +List<Etiqueta> Filtrar
    +elegirEtiquetas()
    +localizarPost
}

class Comentario{
    +String ID
    +Post post
    +Usuario creador
    +String contenido
    +Date fechaCreacion
}

class Like{
    +String ID
    +Post post
    +Usuario usuario
    +Date DateTime
}

Comunidad o-- UsuarioRegistrado
Comunidad o-- Post
UsuarioRegistrado <--> Post
UsuarioInvitado <|-- UsuarioRegistrado
UsuarioRegistrado <|-- Moderador
Post o--o Etiqueta
Post *-- Like
Post *-- Comentario
Post ..> Filtro
Filtro .> Etiqueta


@enduml