@startuml
left to right direction
actor Usuario_Registrado

rectangle "Aplicación" {
    usecase "Cerrar sesión" as UC1
    
    rectangle "Comunidad"{
        usecase "Entrar a comunidad" as UC8
        usecase "Salir de comunidad" as UC9
        usecase "Crear Comunidad" as UC10
}
    usecase "Filtrar contenido" as UC11
    usecase "Modificar datos de usuario" as UC12

}

Usuario_Registrado --> UC1
Usuario_Registrado --> UC8
Usuario_Registrado --> UC9
Usuario_Registrado --> UC10
Usuario_Registrado --> UC11
Usuario_Registrado --> UC12
@enduml
